# Book settings
title: General Physics
author: Dr. Justin Dressel
copyright: "2020"
logo: images/cradle.gif
only_build_toc_files: true
exclude_patterns: [README.md]

html:
  favicon: images/favicon.ico
  extra_navbar: ""
  extra_footer: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>


repository:
  url: https://github.com/justindressel/generalphysics

latex:
  latex_documents:
    targetname: generalphysics.tex
